### ISSUE TITLE
Does it support semantic highlighting?

### ISSUE THREAD

**Issue by singularitti** [huytd/vscode-forest-all-nighter#1]
What a beautiful theme! Does it support semantic highlighting? It does not seem to be, currently.

**Comment by huytd** [comment]
Thanks. This theme does not explicit support semantic highlighting yet (i'm gonna push an update for it). But in the meantime, you can force enable semantic highlighting in your VSCode by setting the following to true:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/613943/95546294-0a366680-09b5-11eb-9f9f-bdd0dec7ef98.png">

**Comment by huytd** [comment]
You can udpate to `v0.0.2`, it should works now:

Before:

![image](https://user-images.githubusercontent.com/613943/95547971-f8ef5900-09b8-11eb-92ac-80e6eb703318.png)

After:

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/613943/95547961-effe8780-09b8-11eb-8de2-8e4f79406cc6.png">

**Comment by singularitti** [comment]
Great, thank you so much!
